# Generated by Django 4.1.5 on 2023-05-27 00:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Tipologia', models.CharField(max_length=100)),
                ('Creditos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'ASignaturas',
                'db_table': 'Asignatura',
            },
        ),
        migrations.CreateModel(
            name='Cita_Inscripcion',
            fields=[
                ('Id_cita', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
            ],
            options={
                'verbose_name': 'Cita_Inscripcion',
                'verbose_name_plural': 'Citas_Inscripcion',
                'db_table': 'Cita_Inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Id_departamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Id_docente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Ocasional', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('Id_estudiante', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Peama', models.BooleanField(help_text='Pertenece al grupo Peama')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('Id_Facultad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.departamento')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'Facultad',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('Id_grupo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Numero_grupo', models.IntegerField()),
                ('Cupos', models.IntegerField()),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Historial_Academico',
            fields=[
                ('Id_Historial', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Papa', models.FloatField()),
                ('Papi', models.FloatField()),
                ('Pa', models.FloatField()),
                ('Matriculas', models.IntegerField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Historial_Academico',
                'verbose_name_plural': 'Historiales_Academicos',
                'db_table': 'Historial_Academico',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('ID_sede', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'Sede',
            },
        ),
        migrations.CreateModel(
            name='Resumen_Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creditos_Exigidos', models.IntegerField()),
                ('Creditos_Aprobados', models.IntegerField()),
                ('Pendientes', models.IntegerField()),
                ('Inscritos', models.IntegerField()),
                ('Cursados', models.IntegerField()),
                ('Historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.historial_academico')),
            ],
            options={
                'verbose_name': 'Resumen_Credito',
                'verbose_name_plural': 'Resumen_Creditos',
                'db_table': 'Resumen_Credito',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('Id_residencia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Estrato', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Ciudad', models.CharField(max_length=50)),
                ('Calle', models.CharField(max_length=255)),
                ('Numero', models.IntegerField()),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
                'db_table': 'Residencia',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('Codigo_SNIES', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Creditos_exigidos', models.IntegerField()),
                ('Grado_licenciatura', models.CharField(choices=[('pregrado', 'Pregrado'), ('posgrado', 'Posgrado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=60)),
                ('Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.facultad')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'Programa',
            },
        ),
        migrations.CreateModel(
            name='Persona_vinculada',
            fields=[
                ('Documento', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Tipo_Documento', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=1)),
                ('Correo_Personal', models.EmailField(max_length=254)),
                ('Telefono', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Nacionalidad', models.CharField(max_length=50)),
                ('Correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('Fecha_Vinculacion', models.DateField()),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona_vinculada',
                'verbose_name_plural': 'Persona_vinculadas',
                'db_table': 'Persona_vinculada',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion_cancelacion',
            fields=[
                ('Id_incripcion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Creditos_Disponibles', models.IntegerField()),
                ('Semestre', models.IntegerField()),
                ('Cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.cita_inscripcion')),
                ('grupo', models.ManyToManyField(to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Inscripcion_cancelacion',
                'verbose_name_plural': 'Inscripciones_cancelaciones',
                'db_table': 'Inscripcion_cancelacion',
            },
        ),
        migrations.AddField(
            model_name='historial_academico',
            name='Programa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.programa'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Persona_Vinculada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.persona_vinculada'),
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('Id_espacio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dia', models.DateField()),
                ('Hora', models.TimeField()),
                ('Edificio', models.CharField(max_length=100)),
                ('Salon', models.IntegerField()),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='Persona_Vinculada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.persona_vinculada'),
        ),
        migrations.AddField(
            model_name='docente',
            name='Sede',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.sede'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sede'),
        ),
        migrations.CreateModel(
            name='Decano',
            fields=[
                ('Id_decano', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Ejerciendo', models.BooleanField(default=True)),
                ('Docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
            ],
            options={
                'verbose_name': 'Decano',
                'verbose_name_plural': 'Decanos',
                'db_table': 'Decano',
            },
        ),
        migrations.CreateModel(
            name='Cupo_Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creditos_Adicionales', models.IntegerField()),
                ('Cupo_Creditos', models.IntegerField()),
                ('Creditos_Disponibles', models.IntegerField()),
                ('Creditos_Doble_titulacion', models.IntegerField()),
                ('Historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.historial_academico')),
            ],
            options={
                'verbose_name': 'Cupo_Credito',
                'verbose_name_plural': 'Cupo_Creditos',
                'db_table': 'Cupo_Credito',
            },
        ),
        migrations.AddField(
            model_name='cita_inscripcion',
            name='Historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.historial_academico'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='Programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.programa'),
        ),
    ]
