# Generated by Django 4.1.5 on 2023-05-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('Id_Nota', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Primer_Corte', models.FloatField(null=True)),
                ('Segundo_Corte', models.FloatField(null=True)),
                ('Tercer_Corte', models.FloatField(null=True)),
                ('Nota_Definitiva', models.FloatField(null=True)),
                ('Aprobada', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'Notas',
            },
        ),
        migrations.RemoveField(
            model_name='inscripcion_cancelacion',
            name='grupo',
        ),
    ]
