# Generated by Django 4.1.5 on 2023-05-20 01:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona_vinculada',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='persona_vinculada',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='persona_vinculada',
            name='Documento',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
