# Generated by Django 4.1.5 on 2023-05-27 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_notas_remove_inscripcion_cancelacion_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion_cancelacion_grupo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
                ('Inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.inscripcion_cancelacion')),
            ],
            options={
                'verbose_name': 'Inscripcion_cancelacion_grupo',
                'verbose_name_plural': 'Inscripcion_cancelacion_grupos',
                'db_table': 'Inscripcion_cancelacion_grupo',
            },
        ),
        migrations.AddField(
            model_name='notas',
            name='Inscripcion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academico.inscripcion_cancelacion_grupo'),
            preserve_default=False,
        ),
    ]
