# Generated by Django 4.1.5 on 2023-05-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_rename_phone_number_persona_vinculada_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('Id_estudiante', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Peama', models.BooleanField(help_text='Pertenece al grupo Peama')),
                ('Persona_Vinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.persona_vinculada')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
            },
        ),
    ]
