# Generated by Django 4.1.5 on 2023-05-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_inscripcion_cancelacion_grupo_notas_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='Historial',
            field=models.ManyToManyField(to='academico.historial_academico'),
        ),
    ]
