# Generated by Django 4.1.5 on 2023-05-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_estudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona_vinculada',
            options={'verbose_name': 'Persona_vinculada', 'verbose_name_plural': 'Persona_vinculadas'},
        ),
        migrations.AlterModelTable(
            name='persona_vinculada',
            table='Persona_vinculada',
        ),
    ]
