# Generated by Django 4.1.5 on 2023-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_notas_historial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='notas',
            name='Nota_Definitiva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Primer_Corte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Segundo_Corte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Tercer_Corte',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
