# Generated by Django 4.1.5 on 2023-05-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_notas_options_alter_notas_nota_definitiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupo_creditos',
            name='Creditos_Disponibles',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='historial_academico',
            name='Pa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historial_academico',
            name='Papa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historial_academico',
            name='Papi',
            field=models.FloatField(default=0.0),
        ),
    ]
