# Generated by Django 4.1.5 on 2023-05-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_cupo_creditos_creditos_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen_creditos',
            name='Creditos_Aprobados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumen_creditos',
            name='Creditos_Exigidos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumen_creditos',
            name='Cursados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumen_creditos',
            name='Inscritos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resumen_creditos',
            name='Pendientes',
            field=models.IntegerField(null=True),
        ),
    ]
