# Generated by Django 4.1.5 on 2023-05-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_residencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencia',
            old_name='name',
            new_name='Estudiante',
        ),
    ]
