# Generated by Django 4.1.5 on 2023-05-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_rename_name_residencia_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Id_departamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('Id_Facultad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.departamento')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'Facultad',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('ID_sede', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'Sede',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('Codigo_SNIES', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Creditos_exigidos', models.IntegerField()),
                ('Grado_licenciatura', models.CharField(choices=[('pregrado', 'Pregrado'), ('posgrado', 'Posgrado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=60)),
                ('Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.facultad')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'Programa',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.sede'),
        ),
    ]
