# Generated by Django 4.1.5 on 2023-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_resumen_creditos_creditos_aprobados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupo_creditos',
            name='Creditos_Adicionales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cupo_creditos',
            name='Creditos_Doble_titulacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cupo_creditos',
            name='Cupo_Creditos',
            field=models.IntegerField(default=0),
        ),
    ]
