# Generated by Django 4.1.5 on 2023-05-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0008_departamento_facultad_sede_programa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Tipologia', models.CharField(max_length=100)),
                ('Creditos', models.IntegerField()),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.programa')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'ASignaturas',
                'db_table': 'Asignatura',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('Id_grupo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Numero_grupo', models.IntegerField()),
                ('Cupos', models.IntegerField()),
                ('Asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.asignatura')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Id_docente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Ocasional', models.BooleanField(default=False)),
                ('Persona_Vinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.persona_vinculada')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.sede')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='Decano',
            fields=[
                ('Id_decano', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Ejerciendo', models.BooleanField(default=True)),
                ('Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.docente')),
            ],
            options={
                'verbose_name': 'Decano',
                'verbose_name_plural': 'Decanos',
                'db_table': 'Decano',
            },
        ),
    ]
