# Generated by Django 4.1.5 on 2023-05-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_asignatura_grupo_docente_decano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita_Inscripcion',
            fields=[
                ('Id_cita', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
            ],
            options={
                'verbose_name': 'Cita_Inscripcion',
                'verbose_name_plural': 'Citas_Inscripcion',
                'db_table': 'Cita_Inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Historial_Academico',
            fields=[
                ('Id_Historial', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Papa', models.FloatField()),
                ('Papi', models.FloatField()),
                ('Pa', models.FloatField()),
                ('Matriculas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Historial_Academico',
                'verbose_name_plural': 'Historiales_Academicos',
                'db_table': 'Historial_Academico',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='Profesor',
            field=models.ManyToManyField(to='Academico.docente'),
        ),
        migrations.AlterField(
            model_name='decano',
            name='Docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='Persona_Vinculada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.persona_vinculada'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='Sede',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.sede'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Persona_Vinculada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.persona_vinculada'),
        ),
        migrations.CreateModel(
            name='Resumen_Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creditos_Exigidos', models.IntegerField()),
                ('Creditos_Aprobados', models.IntegerField()),
                ('Pendientes', models.IntegerField()),
                ('Inscritos', models.IntegerField()),
                ('Cursados', models.IntegerField()),
                ('Historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.historial_academico')),
            ],
            options={
                'verbose_name': 'Resumen_Credito',
                'verbose_name_plural': 'Resumen_Creditos',
                'db_table': 'Resumen_Credito',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion_cancelacion',
            fields=[
                ('Id_incripcion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Creditos_Disponibles', models.IntegerField()),
                ('Semestre', models.IntegerField()),
                ('Cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.cita_inscripcion')),
            ],
            options={
                'verbose_name': 'Inscripcion_cancelacion',
                'verbose_name_plural': 'Inscripciones_cancelaciones',
                'db_table': 'Inscripcion_cancelacion',
            },
        ),
        migrations.AddField(
            model_name='historial_academico',
            name='Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.estudiante'),
        ),
        migrations.AddField(
            model_name='historial_academico',
            name='Programa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.programa'),
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('Id_espacio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Dia', models.DateField()),
                ('Hora', models.TimeField()),
                ('Edificio', models.CharField(max_length=100)),
                ('Salon', models.IntegerField()),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Cupo_Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creditos_Adicionales', models.IntegerField()),
                ('Cupo_Creditos', models.IntegerField()),
                ('Creditos_Disponibles', models.IntegerField()),
                ('Creditos_Doble_titulacion', models.IntegerField()),
                ('Historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.historial_academico')),
            ],
            options={
                'verbose_name': 'Cupo_Credito',
                'verbose_name_plural': 'Cupo_Creditos',
                'db_table': 'Cupo_Credito',
            },
        ),
        migrations.AddField(
            model_name='cita_inscripcion',
            name='Historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.historial_academico'),
        ),
    ]
