# Generated by Django 4.1.5 on 2023-05-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_pago_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='Dia',
            field=models.CharField(max_length=100),
        ),
    ]
