# Generated by Django 4.1.5 on 2023-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_cita_inscripcion_historial_academico_grupo_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion_cancelacion',
            name='Grupo',
            field=models.ManyToManyField(to='Academico.grupo'),
        ),
    ]
