# Generated by Django 4.1.5 on 2023-05-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_inscripcion_cancelacion_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion_cancelacion',
            old_name='Grupo',
            new_name='grupo',
        ),
    ]
